Try Cland and add Arm64.

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -13,17 +13,15 @@ jobs:
       - name: Install Dependencies
         run: |
           brew install make automake bison
-          brew install ncurses readline libxaw
-          # compile_macos_gcc.sh expects this path.  Kludge it.
+          brew install ncurses libxaw
+          # compile_macos_clang.sh expects this path.  Kludge it.
           sudo mkdir -p /opt/X11/include
           sudo ln -s /usr/local/include/freetype2 /opt/X11/include/freetype2
       - name: Build X86_64
         run: |
           PATH='/usr/local/opt/bison/bin:'$PATH
-          ./compile_macos_gcc.sh || true # Will fail to install
+          ./compile_macos_clang.sh || true # Will fail to install
           if [ ! -f release/src/ngspice ]; then false; fi
-          ls -l release/src/xspice/verilog
-          ls -l release/src/xspice/verilog/.libs
       - name: Install X86_64
         run: |
           cd release
@@ -40,4 +38,40 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: Test Macos X86_64
+          path: build
+  build-macos-arm64:
+    runs-on: macos-13
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          repository: gatk555/ngspice
+          ref: ga_test
+      - name: Install Dependencies
+        run: |
+          brew install make automake bison
+          brew install ncurses libxaw
+          # compile_macos_clang.sh expects this path.  Kludge it.
+          sudo mkdir -p /opt/X11/include
+          sudo ln -s /usr/local/include/freetype2 /opt/X11/include/freetype2
+      - name: Build Arm64
+        run: |
+          PATH='/usr/local/opt/bison/bin:'$PATH
+          ./compile_macos_clang.sh || true # Will fail to install
+          if [ ! -f release/src/ngspice ]; then false; fi
+      - name: Install Arm64
+        run: |
+          cd release
+          sudo make install
+          cd ..
+          mkdir build
+          for i in bin lib share ; do
+            mkdir -p build/$i
+            cp -r /usr/local/$i/ngspice build/$i/
+          done
+          echo Copying the examples.
+          cp -r examples/xspice build/share/ngspice
+      - name: Save Arm64
+        uses: actions/upload-artifact@v4
+        with:
+          name: Test Macos Arm64
           path: build
