What was built?

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -25,6 +25,7 @@ jobs:
           cd releasesh
           ../configure  --disable-openmp --enable-cider --with-ngshared CC=clang CFLAGS="-m64 -O2"  LDFLAGS="-m64 -L/usr/local/lib"
           make -j3
+          ls  releasesh/src/.libs
           if [ ! -f releasesh/src/.libs/libngspice.so ]; then false; fi
       - name: Install X86_64
         run: |
@@ -45,6 +46,12 @@ jobs:
           cd examples/shared
           gcc -I../../src/include/ngspice -o shx shx.c
           mv shx ../../build/bin
+      - name: Fail
+        run: |
+          false
+          chmod a+x compile_macos_clang.sh
+          ./compile_macos_clang.sh || true # Will fail to install
+          if [ ! -f release/src/ngspice ]; then false; fi
       - name: Save X86_64
         uses: actions/upload-artifact@v4
         with:
