Try M2 build script.

diff --git a/.github/workflows/macos.yml b/.github/workflows/macos.yml
--- a/.github/workflows/macos.yml
+++ b/.github/workflows/macos.yml
@@ -19,13 +19,10 @@ jobs:
           sudo mkdir -p /opt/X11/include
           sudo ln -s /usr/local/include/freetype2 /opt/X11/include/freetype2
           ls /opt/homebrew/Cellar/readline/8.2.13
-          ls /usr/local/opt/
-          ls /usr/local/opt/readline/
-          ls /usr/local/opt/readline/include
       - name: Build Arm64
         run: |
           PATH='/usr/local/opt/bison/bin:'$PATH
-          ./compile_macos_clang.sh || true # Will fail to install
+          ./compile_macos_clang_M2.sh || true # Will fail to install
           if [ ! -f release/src/ngspice ]; then false; fi
       - name: Install Arm64
         run: |
