Test updated PM build.

diff --git a/.github/workflows/others.yml b/.github/workflows/others.yml
--- a/.github/workflows/others.yml
+++ b/.github/workflows/others.yml
@@ -3,13 +3,58 @@ on:
   workflow_dispatch:
 
 jobs:
+  build-macos-x86_64:
+    runs-on: macos-12
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: gh_pm43
+      - name: Install Dependencies
+        run: |
+          brew install make automake bison
+          brew install ncurses readline libxaw
+          # compile_macos_gcc.sh expects this path.  Kludge it.
+          sudo mkdir -p /opt/X11/include
+          sudo ln -s /usr/local/include/freetype2 /opt/X11/include/freetype2
+      - name: Build X86_64
+        run: |
+          PATH='/usr/local/opt/bison/bin:'$PATH
+          ./compile_macos_gcc.sh || true # Will fail to install
+          if [ ! -f release/src/ngspice ]; then false; fi
+      - name: Install X86_64
+        run: |
+          cd release
+          sudo make install
+          cd ..
+          mkdir build
+          for i in bin lib share ; do
+            mkdir -p build/$i
+            cp -r /usr/local/$i/ngspice build/$i/
+          done
+          echo Copying the examples.
+          cp -r examples build/share/ngspice
+          echo Create README.ngspice
+          echo 'This binary package of ngspice was built at https://github.com/gatk555/ngspice.' > build/README.ngspice
+          echo 'The source code came from the pre-master-43 branch with head revision:' >> build/README.ngspice
+          echo >> build/README.ngspice
+          git log -1 --skip=1 >> build/README.ngspice
+      - name: Save X86_64
+        uses: actions/upload-artifact@v4
+        with:
+          name: Ngspice pre-master-43, Macos X86_64
+          path: build
+      - name: Clean
+        run: |
+          rm -rf release build
+          for i in bin lib share ; do
+            sudo rm -rf /usr/local/$i/ngspice
+          done
   build-macos-arm64:
     runs-on: macos-12
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
         with:
-          repository: gatk555/ngspice
-          ref: gh_pm42
+          ref: gh_pm43
       - name: Install Dependencies
         run: |
           brew install automake bison
@@ -25,7 +70,12 @@ jobs:
       - name: Build arm64
         run: |
           PATH='/usr/local/opt/bison/bin:'$PATH
-          MORE_CONFIG='--host arm64' MORE_CFLAGS='-arch arm64' ./compile_macos_clang.sh || true # Will fail to install
+          ./autogen.sh
+          ls -l
+          mkdir release
+          cd release
+          ../configure --host arm64 --with-x --enable-xspice --enable-cider --enable-predictor --enable-osdi --enable-klu --with-readline=/usr/local/opt/readline CFLAGS="--arch arm64 -m64 -O0 -g -Wall -I/opt/X11/include/freetype2 -I/usr/local/opt/readline/include" CXXFLAGS="-m64 -O2 --arch arm64" LDFLAGS="-m64 -g -L/usr/local/opt/readline/lib -L/opt/X11/lib"
+          make
           if [ ! -f release/src/ngspice ]; then false; fi
       - name: Install arm64
         run: |
@@ -41,11 +91,11 @@ jobs:
           mv examples build/share/ngspice
           echo Create README.ngspice
           echo 'This binary package of ngspice was built at https://github.com/gatk555/ngspice.' > build/README.ngspice
-          echo 'The source code came from the pre-master-42 branch with head revision:' >> build/README.ngspice
+          echo 'The source code came from the pre-master-43 branch with head revision:' >> build/README.ngspice
           echo >> build/README.ngspice
           git log -1 --skip=1 >> build/README.ngspice
       - name: Save arm64
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
-          name: Ngspice pre-master-42, Macos arm64
+          name: Ngspice pre-master-43, Macos arm64
           path: build
